api = "0.2"

[buildpack]
id = "feryardiant/wordpress"
name = "WordPress Buildpack"

  [publish.Ignore]
  files = [
    ".editorconfig",
    ".env.example",
    ".gitignore",
    ".github/",
    "composer.json",
    "composer.lock",
    "gulpfile.js",
    "package.json",
    "public/",
    "packages/",
    "resources/",
    "server.php",
    "tests/",
    "yarn.lock"
  ]
