name: Tests and Build

on: [push]
# on:
#   pull_request:
#     branches:
#       - master
#   push:
#     branches:
#       - master

jobs:
  run:
    name: Runs on PHP ${{ matrix.php-versions }} & WP ${{ matrix.wp-versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wp-versions: ['5.0', '5.1', '5.2']
        php-versions: ['7.1', '7.2', '7.3']
    steps:
    - uses: actions/checkout@master
    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        extension-csv: exif, gd, gettext, imagick, mbstring, xmlrpc
    - name: Install dependencies
      env:
        CI: 1
      run: |
        composer require roots/wordpress ${{ matrix.wp-versions }} --no-progress --no-suggest
        npm install
    - name: Check PHP Version
      run: php -v
    - name: Check PHP Extensions
      run: php -m
    - name: Check Composer Version
      run: composer -V
    - name: Check WordPress Version
      run: vendor/bin/wp core version
