name: Tests and Build

on: [push]
# on:
#   pull_request:
#     branches:
#       - master
#   push:
#     branches:
#       - master

jobs:
  run:
    name: Runs on WordPress ${{ matrix.wp-versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.1']
        wp-versions: ['5.0', '5.1', '5.2']
      # exclude:
      #   - php-versions: 7.2
      #     wp-versions: 5.0
    steps:
    - uses: actions/checkout@master
    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        extension-csv: exif, gd, gettext, imagick, mbstring, xmlrpc
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: |
        npm install
        composer require roots/wordpress ${{ matrix.wp-versions }} --no-progress --no-suggest
    - name: Build
      env:
        WP_ENV: testing
      run: |
        cp .env.example .env
        vendor/bin/wp dotenv salts generate
        npx gulp build
